// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: feature-flag.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FeatureFlagCreationClient is the client API for FeatureFlagCreation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeatureFlagCreationClient interface {
	CreateBooleanFeatureFlag(ctx context.Context, in *CreateBooleanFeatureFlagRequest, opts ...grpc.CallOption) (*CreateFeatureFlagResponse, error)
	CreateInt64FeatureFlag(ctx context.Context, in *CreateInt64FeatureFlagRequest, opts ...grpc.CallOption) (*CreateFeatureFlagResponse, error)
}

type featureFlagCreationClient struct {
	cc grpc.ClientConnInterface
}

func NewFeatureFlagCreationClient(cc grpc.ClientConnInterface) FeatureFlagCreationClient {
	return &featureFlagCreationClient{cc}
}

func (c *featureFlagCreationClient) CreateBooleanFeatureFlag(ctx context.Context, in *CreateBooleanFeatureFlagRequest, opts ...grpc.CallOption) (*CreateFeatureFlagResponse, error) {
	out := new(CreateFeatureFlagResponse)
	err := c.cc.Invoke(ctx, "/FeatureFlagCreation/CreateBooleanFeatureFlag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureFlagCreationClient) CreateInt64FeatureFlag(ctx context.Context, in *CreateInt64FeatureFlagRequest, opts ...grpc.CallOption) (*CreateFeatureFlagResponse, error) {
	out := new(CreateFeatureFlagResponse)
	err := c.cc.Invoke(ctx, "/FeatureFlagCreation/CreateInt64FeatureFlag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeatureFlagCreationServer is the server API for FeatureFlagCreation service.
// All implementations must embed UnimplementedFeatureFlagCreationServer
// for forward compatibility
type FeatureFlagCreationServer interface {
	CreateBooleanFeatureFlag(context.Context, *CreateBooleanFeatureFlagRequest) (*CreateFeatureFlagResponse, error)
	CreateInt64FeatureFlag(context.Context, *CreateInt64FeatureFlagRequest) (*CreateFeatureFlagResponse, error)
	mustEmbedUnimplementedFeatureFlagCreationServer()
}

// UnimplementedFeatureFlagCreationServer must be embedded to have forward compatible implementations.
type UnimplementedFeatureFlagCreationServer struct {
}

func (UnimplementedFeatureFlagCreationServer) CreateBooleanFeatureFlag(context.Context, *CreateBooleanFeatureFlagRequest) (*CreateFeatureFlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBooleanFeatureFlag not implemented")
}
func (UnimplementedFeatureFlagCreationServer) CreateInt64FeatureFlag(context.Context, *CreateInt64FeatureFlagRequest) (*CreateFeatureFlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInt64FeatureFlag not implemented")
}
func (UnimplementedFeatureFlagCreationServer) mustEmbedUnimplementedFeatureFlagCreationServer() {}

// UnsafeFeatureFlagCreationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeatureFlagCreationServer will
// result in compilation errors.
type UnsafeFeatureFlagCreationServer interface {
	mustEmbedUnimplementedFeatureFlagCreationServer()
}

func RegisterFeatureFlagCreationServer(s grpc.ServiceRegistrar, srv FeatureFlagCreationServer) {
	s.RegisterService(&FeatureFlagCreation_ServiceDesc, srv)
}

func _FeatureFlagCreation_CreateBooleanFeatureFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBooleanFeatureFlagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureFlagCreationServer).CreateBooleanFeatureFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FeatureFlagCreation/CreateBooleanFeatureFlag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureFlagCreationServer).CreateBooleanFeatureFlag(ctx, req.(*CreateBooleanFeatureFlagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureFlagCreation_CreateInt64FeatureFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInt64FeatureFlagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureFlagCreationServer).CreateInt64FeatureFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FeatureFlagCreation/CreateInt64FeatureFlag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureFlagCreationServer).CreateInt64FeatureFlag(ctx, req.(*CreateInt64FeatureFlagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FeatureFlagCreation_ServiceDesc is the grpc.ServiceDesc for FeatureFlagCreation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeatureFlagCreation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FeatureFlagCreation",
	HandlerType: (*FeatureFlagCreationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBooleanFeatureFlag",
			Handler:    _FeatureFlagCreation_CreateBooleanFeatureFlag_Handler,
		},
		{
			MethodName: "CreateInt64FeatureFlag",
			Handler:    _FeatureFlagCreation_CreateInt64FeatureFlag_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feature-flag.proto",
}
