// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feature-flag.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Environment struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Active               bool     `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Environment) Reset()         { *m = Environment{} }
func (m *Environment) String() string { return proto.CompactTextString(m) }
func (*Environment) ProtoMessage()    {}
func (*Environment) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ea6c3dacc832db1, []int{0}
}

func (m *Environment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Environment.Unmarshal(m, b)
}
func (m *Environment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Environment.Marshal(b, m, deterministic)
}
func (m *Environment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Environment.Merge(m, src)
}
func (m *Environment) XXX_Size() int {
	return xxx_messageInfo_Environment.Size(m)
}
func (m *Environment) XXX_DiscardUnknown() {
	xxx_messageInfo_Environment.DiscardUnknown(m)
}

var xxx_messageInfo_Environment proto.InternalMessageInfo

func (m *Environment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Environment) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type CreateBooleanFeatureFlagRequest struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OnActiveValues       []bool         `protobuf:"varint,3,rep,packed,name=onActiveValues,proto3" json:"onActiveValues,omitempty"`
	Enviroments          []*Environment `protobuf:"bytes,4,rep,name=enviroments,proto3" json:"enviroments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateBooleanFeatureFlagRequest) Reset()         { *m = CreateBooleanFeatureFlagRequest{} }
func (m *CreateBooleanFeatureFlagRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBooleanFeatureFlagRequest) ProtoMessage()    {}
func (*CreateBooleanFeatureFlagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ea6c3dacc832db1, []int{1}
}

func (m *CreateBooleanFeatureFlagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBooleanFeatureFlagRequest.Unmarshal(m, b)
}
func (m *CreateBooleanFeatureFlagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBooleanFeatureFlagRequest.Marshal(b, m, deterministic)
}
func (m *CreateBooleanFeatureFlagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBooleanFeatureFlagRequest.Merge(m, src)
}
func (m *CreateBooleanFeatureFlagRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBooleanFeatureFlagRequest.Size(m)
}
func (m *CreateBooleanFeatureFlagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBooleanFeatureFlagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBooleanFeatureFlagRequest proto.InternalMessageInfo

func (m *CreateBooleanFeatureFlagRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateBooleanFeatureFlagRequest) GetOnActiveValues() []bool {
	if m != nil {
		return m.OnActiveValues
	}
	return nil
}

func (m *CreateBooleanFeatureFlagRequest) GetEnviroments() []*Environment {
	if m != nil {
		return m.Enviroments
	}
	return nil
}

type CreateFeatureFlagResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFeatureFlagResponse) Reset()         { *m = CreateFeatureFlagResponse{} }
func (m *CreateFeatureFlagResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFeatureFlagResponse) ProtoMessage()    {}
func (*CreateFeatureFlagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ea6c3dacc832db1, []int{2}
}

func (m *CreateFeatureFlagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFeatureFlagResponse.Unmarshal(m, b)
}
func (m *CreateFeatureFlagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFeatureFlagResponse.Marshal(b, m, deterministic)
}
func (m *CreateFeatureFlagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFeatureFlagResponse.Merge(m, src)
}
func (m *CreateFeatureFlagResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFeatureFlagResponse.Size(m)
}
func (m *CreateFeatureFlagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFeatureFlagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFeatureFlagResponse proto.InternalMessageInfo

func (m *CreateFeatureFlagResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateInt64FeatureFlagRequest struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OnActiveValues       []int64        `protobuf:"varint,3,rep,packed,name=onActiveValues,proto3" json:"onActiveValues,omitempty"`
	Enviroments          []*Environment `protobuf:"bytes,4,rep,name=enviroments,proto3" json:"enviroments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateInt64FeatureFlagRequest) Reset()         { *m = CreateInt64FeatureFlagRequest{} }
func (m *CreateInt64FeatureFlagRequest) String() string { return proto.CompactTextString(m) }
func (*CreateInt64FeatureFlagRequest) ProtoMessage()    {}
func (*CreateInt64FeatureFlagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ea6c3dacc832db1, []int{3}
}

func (m *CreateInt64FeatureFlagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateInt64FeatureFlagRequest.Unmarshal(m, b)
}
func (m *CreateInt64FeatureFlagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateInt64FeatureFlagRequest.Marshal(b, m, deterministic)
}
func (m *CreateInt64FeatureFlagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateInt64FeatureFlagRequest.Merge(m, src)
}
func (m *CreateInt64FeatureFlagRequest) XXX_Size() int {
	return xxx_messageInfo_CreateInt64FeatureFlagRequest.Size(m)
}
func (m *CreateInt64FeatureFlagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateInt64FeatureFlagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateInt64FeatureFlagRequest proto.InternalMessageInfo

func (m *CreateInt64FeatureFlagRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateInt64FeatureFlagRequest) GetOnActiveValues() []int64 {
	if m != nil {
		return m.OnActiveValues
	}
	return nil
}

func (m *CreateInt64FeatureFlagRequest) GetEnviroments() []*Environment {
	if m != nil {
		return m.Enviroments
	}
	return nil
}

func init() {
	proto.RegisterType((*Environment)(nil), "Environment")
	proto.RegisterType((*CreateBooleanFeatureFlagRequest)(nil), "CreateBooleanFeatureFlagRequest")
	proto.RegisterType((*CreateFeatureFlagResponse)(nil), "CreateFeatureFlagResponse")
	proto.RegisterType((*CreateInt64FeatureFlagRequest)(nil), "CreateInt64FeatureFlagRequest")
}

func init() {
	proto.RegisterFile("feature-flag.proto", fileDescriptor_0ea6c3dacc832db1)
}

var fileDescriptor_0ea6c3dacc832db1 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0xd2, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0x07, 0x70, 0xd2, 0x96, 0x32, 0x5f, 0x65, 0x87, 0x77, 0x18, 0x71, 0xa0, 0x86, 0x1e, 0xa4,
	0x20, 0x46, 0x98, 0x22, 0x78, 0x74, 0xe2, 0xc0, 0x6b, 0x10, 0x11, 0x6f, 0x99, 0x7b, 0x1b, 0x85,
	0x2e, 0xa9, 0x4d, 0xba, 0x2f, 0x21, 0x7e, 0x24, 0xbf, 0x9b, 0xd8, 0xee, 0x50, 0x65, 0x9b, 0x87,
	0xdd, 0x92, 0xf0, 0xf8, 0xf3, 0xcb, 0x9f, 0x07, 0x38, 0x27, 0xed, 0xeb, 0x8a, 0x2e, 0xe6, 0x85,
	0x5e, 0xc8, 0xb2, 0xb2, 0xde, 0xa6, 0xb7, 0x90, 0x3c, 0x98, 0x55, 0x5e, 0x59, 0xb3, 0x24, 0xe3,
	0x11, 0x21, 0x32, 0x7a, 0x49, 0x9c, 0x09, 0x96, 0x1d, 0xa8, 0xe6, 0x8c, 0x03, 0x88, 0xf5, 0x9b,
	0xcf, 0x57, 0xc4, 0x03, 0xc1, 0xb2, 0x9e, 0x5a, 0xdf, 0xd2, 0x4f, 0x06, 0xa7, 0xf7, 0x15, 0x69,
	0x4f, 0x63, 0x6b, 0x0b, 0xd2, 0x66, 0xd2, 0xc6, 0x4f, 0x0a, 0xbd, 0x50, 0xf4, 0x5e, 0x93, 0xdb,
	0x9c, 0x77, 0x06, 0x7d, 0x6b, 0xee, 0x9a, 0x8c, 0x67, 0x5d, 0xd4, 0xe4, 0x78, 0x28, 0xc2, 0xac,
	0xa7, 0xfe, 0xbc, 0xa2, 0x84, 0x84, 0x1a, 0xda, 0x8f, 0xcc, 0xf1, 0x48, 0x84, 0x59, 0x32, 0x3a,
	0x94, 0x1d, 0xae, 0xea, 0x0e, 0xa4, 0xe7, 0x70, 0xd4, 0x72, 0x7e, 0x39, 0x5c, 0x69, 0x8d, 0x23,
	0xec, 0x43, 0x90, 0xcf, 0xd6, 0x8c, 0x20, 0x9f, 0xa5, 0x1f, 0x0c, 0x8e, 0xdb, 0xe9, 0x47, 0xe3,
	0x6f, 0xae, 0xf7, 0xa2, 0x87, 0xfb, 0xd2, 0x47, 0x5f, 0x0c, 0x92, 0x0e, 0x01, 0x5f, 0x80, 0x6f,
	0x6b, 0x16, 0x85, 0xfc, 0xa7, 0xf4, 0xe1, 0x50, 0x6e, 0xef, 0xe1, 0x09, 0x06, 0x9b, 0xbf, 0x8d,
	0x27, 0x72, 0x67, 0x1f, 0xbb, 0x52, 0xc7, 0xf1, 0x6b, 0x24, 0x2f, 0xcb, 0xe9, 0x34, 0x6e, 0x96,
	0xea, 0xea, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x51, 0xf0, 0x7c, 0x09, 0x6a, 0x02, 0x00, 0x00,
}
