// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: feature-flag.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FeatureFlagClient is the client API for FeatureFlag service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeatureFlagClient interface {
	CreateBooleanFeatureFlag(ctx context.Context, in *CreateBooleanFeatureFlagRequest, opts ...grpc.CallOption) (*CreateBooleanFeatureFlagResponse, error)
}

type featureFlagClient struct {
	cc grpc.ClientConnInterface
}

func NewFeatureFlagClient(cc grpc.ClientConnInterface) FeatureFlagClient {
	return &featureFlagClient{cc}
}

func (c *featureFlagClient) CreateBooleanFeatureFlag(ctx context.Context, in *CreateBooleanFeatureFlagRequest, opts ...grpc.CallOption) (*CreateBooleanFeatureFlagResponse, error) {
	out := new(CreateBooleanFeatureFlagResponse)
	err := c.cc.Invoke(ctx, "/FeatureFlag/CreateBooleanFeatureFlag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeatureFlagServer is the server API for FeatureFlag service.
// All implementations must embed UnimplementedFeatureFlagServer
// for forward compatibility
type FeatureFlagServer interface {
	CreateBooleanFeatureFlag(context.Context, *CreateBooleanFeatureFlagRequest) (*CreateBooleanFeatureFlagResponse, error)
	mustEmbedUnimplementedFeatureFlagServer()
}

// UnimplementedFeatureFlagServer must be embedded to have forward compatible implementations.
type UnimplementedFeatureFlagServer struct {
}

func (UnimplementedFeatureFlagServer) CreateBooleanFeatureFlag(context.Context, *CreateBooleanFeatureFlagRequest) (*CreateBooleanFeatureFlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBooleanFeatureFlag not implemented")
}
func (UnimplementedFeatureFlagServer) mustEmbedUnimplementedFeatureFlagServer() {}

// UnsafeFeatureFlagServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeatureFlagServer will
// result in compilation errors.
type UnsafeFeatureFlagServer interface {
	mustEmbedUnimplementedFeatureFlagServer()
}

func RegisterFeatureFlagServer(s grpc.ServiceRegistrar, srv FeatureFlagServer) {
	s.RegisterService(&FeatureFlag_ServiceDesc, srv)
}

func _FeatureFlag_CreateBooleanFeatureFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBooleanFeatureFlagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureFlagServer).CreateBooleanFeatureFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FeatureFlag/CreateBooleanFeatureFlag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureFlagServer).CreateBooleanFeatureFlag(ctx, req.(*CreateBooleanFeatureFlagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FeatureFlag_ServiceDesc is the grpc.ServiceDesc for FeatureFlag service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeatureFlag_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FeatureFlag",
	HandlerType: (*FeatureFlagServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBooleanFeatureFlag",
			Handler:    _FeatureFlag_CreateBooleanFeatureFlag_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feature-flag.proto",
}
