// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feature-flag.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BooleanEnviroment struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Active               bool     `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	OnActiveValues       []bool   `protobuf:"varint,3,rep,packed,name=onActiveValues,proto3" json:"onActiveValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BooleanEnviroment) Reset()         { *m = BooleanEnviroment{} }
func (m *BooleanEnviroment) String() string { return proto.CompactTextString(m) }
func (*BooleanEnviroment) ProtoMessage()    {}
func (*BooleanEnviroment) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ea6c3dacc832db1, []int{0}
}

func (m *BooleanEnviroment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BooleanEnviroment.Unmarshal(m, b)
}
func (m *BooleanEnviroment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BooleanEnviroment.Marshal(b, m, deterministic)
}
func (m *BooleanEnviroment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BooleanEnviroment.Merge(m, src)
}
func (m *BooleanEnviroment) XXX_Size() int {
	return xxx_messageInfo_BooleanEnviroment.Size(m)
}
func (m *BooleanEnviroment) XXX_DiscardUnknown() {
	xxx_messageInfo_BooleanEnviroment.DiscardUnknown(m)
}

var xxx_messageInfo_BooleanEnviroment proto.InternalMessageInfo

func (m *BooleanEnviroment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BooleanEnviroment) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *BooleanEnviroment) GetOnActiveValues() []bool {
	if m != nil {
		return m.OnActiveValues
	}
	return nil
}

type CreateBooleanFeatureFlagRequest struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Active               bool                 `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	Enviroments          []*BooleanEnviroment `protobuf:"bytes,3,rep,name=enviroments,proto3" json:"enviroments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateBooleanFeatureFlagRequest) Reset()         { *m = CreateBooleanFeatureFlagRequest{} }
func (m *CreateBooleanFeatureFlagRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBooleanFeatureFlagRequest) ProtoMessage()    {}
func (*CreateBooleanFeatureFlagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ea6c3dacc832db1, []int{1}
}

func (m *CreateBooleanFeatureFlagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBooleanFeatureFlagRequest.Unmarshal(m, b)
}
func (m *CreateBooleanFeatureFlagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBooleanFeatureFlagRequest.Marshal(b, m, deterministic)
}
func (m *CreateBooleanFeatureFlagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBooleanFeatureFlagRequest.Merge(m, src)
}
func (m *CreateBooleanFeatureFlagRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBooleanFeatureFlagRequest.Size(m)
}
func (m *CreateBooleanFeatureFlagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBooleanFeatureFlagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBooleanFeatureFlagRequest proto.InternalMessageInfo

func (m *CreateBooleanFeatureFlagRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateBooleanFeatureFlagRequest) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *CreateBooleanFeatureFlagRequest) GetEnviroments() []*BooleanEnviroment {
	if m != nil {
		return m.Enviroments
	}
	return nil
}

type CreateBooleanFeatureFlagResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBooleanFeatureFlagResponse) Reset()         { *m = CreateBooleanFeatureFlagResponse{} }
func (m *CreateBooleanFeatureFlagResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBooleanFeatureFlagResponse) ProtoMessage()    {}
func (*CreateBooleanFeatureFlagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ea6c3dacc832db1, []int{2}
}

func (m *CreateBooleanFeatureFlagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBooleanFeatureFlagResponse.Unmarshal(m, b)
}
func (m *CreateBooleanFeatureFlagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBooleanFeatureFlagResponse.Marshal(b, m, deterministic)
}
func (m *CreateBooleanFeatureFlagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBooleanFeatureFlagResponse.Merge(m, src)
}
func (m *CreateBooleanFeatureFlagResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBooleanFeatureFlagResponse.Size(m)
}
func (m *CreateBooleanFeatureFlagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBooleanFeatureFlagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBooleanFeatureFlagResponse proto.InternalMessageInfo

func (m *CreateBooleanFeatureFlagResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*BooleanEnviroment)(nil), "BooleanEnviroment")
	proto.RegisterType((*CreateBooleanFeatureFlagRequest)(nil), "CreateBooleanFeatureFlagRequest")
	proto.RegisterType((*CreateBooleanFeatureFlagResponse)(nil), "CreateBooleanFeatureFlagResponse")
}

func init() {
	proto.RegisterFile("feature-flag.proto", fileDescriptor_0ea6c3dacc832db1)
}

var fileDescriptor_0ea6c3dacc832db1 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0x4b, 0x4d, 0x2c,
	0x29, 0x2d, 0x4a, 0xd5, 0x4d, 0xcb, 0x49, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x4a,
	0xe7, 0x12, 0x74, 0xca, 0xcf, 0xcf, 0x49, 0x4d, 0xcc, 0x73, 0xcd, 0x2b, 0xcb, 0x2c, 0xca, 0xcf,
	0x4d, 0xcd, 0x2b, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x02, 0xb3, 0x85, 0xc4, 0xb8, 0xd8, 0x12, 0x93, 0x4b, 0x32, 0xcb, 0x52, 0x25, 0x98,
	0x14, 0x18, 0x35, 0x38, 0x82, 0xa0, 0x3c, 0x21, 0x35, 0x2e, 0xbe, 0xfc, 0x3c, 0x47, 0x30, 0x3b,
	0x2c, 0x31, 0xa7, 0x34, 0xb5, 0x58, 0x82, 0x59, 0x81, 0x59, 0x83, 0x23, 0x08, 0x4d, 0x54, 0xa9,
	0x99, 0x91, 0x4b, 0xde, 0xb9, 0x28, 0x35, 0xb1, 0x24, 0x15, 0x6a, 0x9f, 0x1b, 0xc4, 0x31, 0x6e,
	0x39, 0x89, 0xe9, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0xa4, 0xd9, 0x6b, 0xc2, 0xc5, 0x9d, 0x0a,
	0x77, 0x31, 0xc4, 0x52, 0x6e, 0x23, 0x21, 0x3d, 0x0c, 0xcf, 0x04, 0x21, 0x2b, 0x53, 0x32, 0xe2,
	0x52, 0xc0, 0xed, 0x88, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14,
	0xa8, 0x1b, 0x98, 0x32, 0x53, 0x8c, 0xf2, 0xb8, 0xb8, 0x91, 0x94, 0x09, 0xc5, 0x73, 0x49, 0xe0,
	0x32, 0x42, 0x48, 0x41, 0x8f, 0x80, 0x17, 0xa5, 0x14, 0xf5, 0x08, 0xd9, 0xef, 0xc4, 0x16, 0xc5,
	0xa2, 0xa7, 0x5f, 0x90, 0x94, 0xc4, 0x06, 0x8e, 0x21, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xf7, 0xe3, 0x50, 0xc5, 0xb7, 0x01, 0x00, 0x00,
}
