// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feature-flag.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Environment struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Active               bool     `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Environment) Reset()         { *m = Environment{} }
func (m *Environment) String() string { return proto.CompactTextString(m) }
func (*Environment) ProtoMessage()    {}
func (*Environment) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ea6c3dacc832db1, []int{0}
}

func (m *Environment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Environment.Unmarshal(m, b)
}
func (m *Environment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Environment.Marshal(b, m, deterministic)
}
func (m *Environment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Environment.Merge(m, src)
}
func (m *Environment) XXX_Size() int {
	return xxx_messageInfo_Environment.Size(m)
}
func (m *Environment) XXX_DiscardUnknown() {
	xxx_messageInfo_Environment.DiscardUnknown(m)
}

var xxx_messageInfo_Environment proto.InternalMessageInfo

func (m *Environment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Environment) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type CreateBooleanFeatureFlagRequest struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Active               bool           `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	OnActiveValues       []bool         `protobuf:"varint,3,rep,packed,name=onActiveValues,proto3" json:"onActiveValues,omitempty"`
	Enviroments          []*Environment `protobuf:"bytes,4,rep,name=enviroments,proto3" json:"enviroments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateBooleanFeatureFlagRequest) Reset()         { *m = CreateBooleanFeatureFlagRequest{} }
func (m *CreateBooleanFeatureFlagRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBooleanFeatureFlagRequest) ProtoMessage()    {}
func (*CreateBooleanFeatureFlagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ea6c3dacc832db1, []int{1}
}

func (m *CreateBooleanFeatureFlagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBooleanFeatureFlagRequest.Unmarshal(m, b)
}
func (m *CreateBooleanFeatureFlagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBooleanFeatureFlagRequest.Marshal(b, m, deterministic)
}
func (m *CreateBooleanFeatureFlagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBooleanFeatureFlagRequest.Merge(m, src)
}
func (m *CreateBooleanFeatureFlagRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBooleanFeatureFlagRequest.Size(m)
}
func (m *CreateBooleanFeatureFlagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBooleanFeatureFlagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBooleanFeatureFlagRequest proto.InternalMessageInfo

func (m *CreateBooleanFeatureFlagRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateBooleanFeatureFlagRequest) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *CreateBooleanFeatureFlagRequest) GetOnActiveValues() []bool {
	if m != nil {
		return m.OnActiveValues
	}
	return nil
}

func (m *CreateBooleanFeatureFlagRequest) GetEnviroments() []*Environment {
	if m != nil {
		return m.Enviroments
	}
	return nil
}

type CreateBooleanFeatureFlagResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBooleanFeatureFlagResponse) Reset()         { *m = CreateBooleanFeatureFlagResponse{} }
func (m *CreateBooleanFeatureFlagResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBooleanFeatureFlagResponse) ProtoMessage()    {}
func (*CreateBooleanFeatureFlagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ea6c3dacc832db1, []int{2}
}

func (m *CreateBooleanFeatureFlagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBooleanFeatureFlagResponse.Unmarshal(m, b)
}
func (m *CreateBooleanFeatureFlagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBooleanFeatureFlagResponse.Marshal(b, m, deterministic)
}
func (m *CreateBooleanFeatureFlagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBooleanFeatureFlagResponse.Merge(m, src)
}
func (m *CreateBooleanFeatureFlagResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBooleanFeatureFlagResponse.Size(m)
}
func (m *CreateBooleanFeatureFlagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBooleanFeatureFlagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBooleanFeatureFlagResponse proto.InternalMessageInfo

func (m *CreateBooleanFeatureFlagResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Environment)(nil), "Environment")
	proto.RegisterType((*CreateBooleanFeatureFlagRequest)(nil), "CreateBooleanFeatureFlagRequest")
	proto.RegisterType((*CreateBooleanFeatureFlagResponse)(nil), "CreateBooleanFeatureFlagResponse")
}

func init() {
	proto.RegisterFile("feature-flag.proto", fileDescriptor_0ea6c3dacc832db1)
}

var fileDescriptor_0ea6c3dacc832db1 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xbf, 0x4e, 0xc3, 0x40,
	0x0c, 0xc6, 0x95, 0x3f, 0x8a, 0x8a, 0x83, 0x3a, 0x78, 0x40, 0x27, 0x16, 0x8e, 0x0c, 0x28, 0x0b,
	0x87, 0x14, 0x26, 0x46, 0x8a, 0xe8, 0x03, 0xdc, 0xc0, 0xc0, 0x82, 0x5c, 0xea, 0x56, 0x91, 0x52,
	0x5f, 0xc8, 0x5d, 0xfa, 0x46, 0xbc, 0x27, 0xe2, 0xe8, 0x10, 0x21, 0x55, 0x55, 0xb7, 0xcf, 0xd6,
	0xa7, 0xcf, 0x3f, 0xdb, 0x80, 0x1b, 0xa6, 0x30, 0x0e, 0x7c, 0xbf, 0xe9, 0x68, 0x6b, 0xfa, 0xc1,
	0x05, 0x57, 0x3d, 0x41, 0xf9, 0x2a, 0xfb, 0x76, 0x70, 0xb2, 0x63, 0x09, 0x88, 0x90, 0x0b, 0xed,
	0x58, 0x25, 0x3a, 0xa9, 0x2f, 0x6c, 0xd4, 0x78, 0x05, 0x05, 0x7d, 0x86, 0x76, 0xcf, 0x2a, 0xd5,
	0x49, 0x3d, 0xb3, 0x87, 0xaa, 0xfa, 0x4e, 0xe0, 0xe6, 0x65, 0x60, 0x0a, 0xbc, 0x70, 0xae, 0x63,
	0x92, 0xe5, 0x5f, 0xfc, 0xb2, 0xa3, 0xad, 0xe5, 0xaf, 0x91, 0xfd, 0x59, 0x79, 0x78, 0x07, 0x73,
	0x27, 0xcf, 0x51, 0xbf, 0x51, 0x37, 0xb2, 0x57, 0x99, 0xce, 0xea, 0x99, 0xfd, 0xd7, 0x45, 0x03,
	0x25, 0x47, 0xe4, 0x5f, 0x62, 0xaf, 0x72, 0x9d, 0xd5, 0x65, 0x73, 0x69, 0x26, 0x6b, 0xd8, 0xa9,
	0xa1, 0x6a, 0x40, 0x1f, 0xc7, 0xf4, 0xbd, 0x13, 0xcf, 0x38, 0x87, 0xb4, 0x5d, 0x1f, 0x28, 0xd3,
	0x76, 0xdd, 0x08, 0x94, 0x13, 0x1b, 0x7e, 0x80, 0x3a, 0x16, 0x81, 0xda, 0x9c, 0x38, 0xc2, 0xf5,
	0xad, 0x39, 0x35, 0x7f, 0x51, 0xbc, 0xe7, 0xe6, 0xa1, 0x5f, 0xad, 0x8a, 0xf8, 0x95, 0xc7, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xaa, 0xd1, 0x29, 0xab, 0x01, 0x00, 0x00,
}
